from lao_alphabets import Lao_alphabets

test = Lao_alphabets()
print(test.is_ALPHABETS("a"))
print(test.is_X('ຮ'))
print(test.is_X0('ແ'))
print(test.is_X1('ຫ'))
print(test.is_X2('ວ'))
print(test.is_X3('ູ'))
print(test.is_X4('ື'))
print(test.is_X5('້'))
print(test.is_X6('ຽ'))
print(test.is_X7('ຳ'))
print(test.is_X7_2('ະ'))
print(test.is_X8('ງ'))
print(test.is_X9('ພ'))
print(test.is_X10('ໆ'))
print(test.is_MixConsonants('ຈ'))
print(test.is_SPECIALCHARS("1"))
